version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages:/app/packages
    restart: unless-stopped
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/web/src:/app/apps/web/src
      - ./packages:/app/packages
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge